### ISSUE TITLE
Shurima and Empires of the Ascended expansion

### ISSUE THREAD

**Issue by paaksing** [Rafalonso/LoRDeckCodesPython#10]
See detailed changes in a PR made on C# library
https://github.com/RiotGames/LoRDeckCodes/pull/57/files
This PR is waiting for approve but it gives a better idea.

- New region SH (Shurima).
- Empires of the Ascended expansion of Shurima.
- Example shurima cards (Posted by Gene as card reveal 4):
  * 04SH028    February 21
  * 04SH014    February 21
  * 04SH001    February 21
  * 04SH011    February 21
  * 04SH091    February 21
  * 04SH021    February 21
  * 04SH013    February 21
  * 04SH031    February 21

**Comment by Rafalonso** [comment]
Will add these changes either today or tomorrow, thanks for the heads-up

**Comment by paaksing** [comment]
Maybe wait for the PR to be accepted or actual change is made on the C# library.

**Comment by paaksing** [comment]
Shurima will be out by Tuesday/Wednesday

**Comment by paaksing** [comment]
Hi @Rafalonso, Shurima is live, and the PR was accepted

**Comment by Azg-stdio** [comment]
Hi @Rafalonso, I'm using your repository on my app: https://www.lorstats.com and it's really helpful, thank you for your work!

I wanted to know if you are going to update the repo to support Shurima Cards.

**Comment by Rafalonso** [comment]
I've been lazy, will do it today @Azg-stdio

**Comment by Azg-stdio** [comment]
Thanks a lot!

**Comment by Rafalonso** [comment]
Version 3 has been released, thanks for the ticket

**Comment by Azg-stdio** [comment]
Hi @Rafalonso Sorry to ask again

Apparently, most of the cards are working correctly but some cases are not handled correctly, for example:

CMBQCBAHCQBAIAYCAQDQCAYICAJRUHZIGUBAEAIDBQMAGBADAEBQ6AA

This deck code I think contains Sivir and I got 04None020 instead.

Thank you

**Comment by Azg-stdio** [comment]
This deck has 3 wrong formatted ones: CMCQCBAFAMBAEBIEAYBQGBIDAQDAGBAHAMCRUBABAUFSUMBRAAAQCAIFEY

**Comment by Rafalonso** [comment]
@Azg-stdio Are you sure you've updated lor_deckcodes to 3.0.0? Mine is reading correctly:
```
>>> ooo = lor_deckcodes.LoRDeck.from_deckcode("CMBQCBAHCQBAIAYCAQDQCAYICAJRUHZIGUBAEAIDBQMAGBADAEBQ6AA")
>>> list(ooo)
['3:04SH020', '3:04NX002', '3:04NX004', '3:01NX008', '3:01NX016', '3:01NX019', '3:01NX026', '3:01NX031', '3:01NX040', '3:01NX053', '2:01NX012', '2:01NX024', '2:04NX001', '2:04NX003', '2:04NX015']
>>> 
```

**Comment by Azg-stdio** [comment]
Oh, sorry that was my bad, I updated it on my local env but didn't change the requirements.txt of my app, lol sorry, thank you!
