### ISSUE TITLE
Set 3 Update Notice

### ISSUE THREAD

**Issue by LiquidRekto** [Rafalonso/LoRDeckCodesPython#5]
Hello there, Riot has recently implemented the code for decoding set 3, so it would be nice if you can take your time updating the code before the third set arrives on August 28th.

**Comment by Rafalonso** [comment]
Hello, thank you for raising this, I will update it either today or
tomorrow, thank you for bringing this to my attention

**Comment by Rafalonso** [comment]
@LiquidRekto Library has been updated. Run pip upgrade for Mount Targon support. If any other issue arises open another ticket. thank you
