### ISSUE TITLE
Integrating to the Pyot Framework

### ISSUE THREAD

**Issue by paaksing** [Rafalonso/LoRDeckCodesPython#6]
As you may noticed, riot has launched the match api for lor. I am the author of [Pyot](https://github.com/paaksing/Pyot), its a framework for the riot api in python including all static files endpoints. I will be using this lib as a dependency for the framework, wanted to get a form of contact (prob discord) faster than github issues since I am not able to find you on the discord server.

**Comment by Rafalonso** [comment]
Hello @paaksing, happy to know you're interested in this lib. My email is available in my GitHub profile in case you want to discuss any further.
Closing the issue as it's not related to this code base.
