### ISSUE TITLE
Format rule for cards with more than 3 copies

### ISSUE THREAD

**Issue by wangyi041228** [Rafalonso/LoRDeckCodesPython#7]
A lot of Expdition decks have cards with more than 3 copies. I wish to encode and decode these decks. :)

Univesal basic format in game:

0001 0010 00000000 00000000 00000000 [copies]+[set]+[region]+[number] *n

00000000 *3 are groups for 3, 2 or 1 copy
[copies] can be 1, 2 or 3

source in C#:
https://github.com/RiotGames/LoRDeckCodes/blob/master/LoRDeckCodes/LoRDeckEncoder.cs

My ugly solution for decoding

(+)(+)(+)
def _decode_card_block_(data_stream: BytesIO) -> List[str]:
    n_card_copies = next_varint(data_stream)
    set_number = next_varint(data_stream)
    faction = next_varint(data_stream)
    num = next_varint(data_stream)
    return [f'{n_card_copies}:{set_number:02}{faction_mapping.get(faction)}{num:03}']
(+)(+)(+)

def decode_deck(deckcode: str):
    ...
    # 1 card copies
    all_cards.extend(_decode_card_block(1, data))
(+)(+)(+)
    # more cards
    n = data.tell()
    c = data.read(1)
    data.seek(n)
    while c:
        all_cards.extend(_decode_card_block_(data))
        n = data.tell()
        c = data.read(1)
        data.seek(n)
(+)(+)(+)
    return all_cards

My ugly solution for encoding:

(+)(+)(+)
def _encode_card_block_(data_stream: BytesIO, cards: List["CardCodeAndCount"]) -> None:
    sorted_cards = sorted(cards, key=lambda y: y.card_code)
    for card in sorted_cards:
        write_varint(data_stream, card.count)
        write_varint(data_stream, card.set)
        write_varint(data_stream, faction_mapping.get(card.faction))
        write_varint(data_stream, card.card_id)
(+)(+)(+)

def encode_deck(cards: List["CardCodeAndCount"]) -> str:
    ...
    # 1 card copies
    one_copies = list(filter(lambda x: x.count == 1, cards))
    _encode_card_block(data, one_copies)
(+)(+)(+)
    more_copies = list(filter(lambda x: x.count > 3, cards))
    _encode_card_block_(data, more_copies)
(+)(+)(+)
    data.seek(0)
    return b32encode(data.read()).decode().replace('=', '')

**Comment by paaksing** [comment]
@wangyi041228 At least ``` your code, it is basically unreadable

**Comment by shaobaili3** [comment]
I help her to open a new pull request. please refer #9 for details.

Thanks

**Comment by Rafalonso** [comment]
Taken care of in #9 thank you very much for contributing
