### ISSUE TITLE
The set/faction lists are ordered by increasing length

### ISSUE THREAD

**Issue by wangyi041228** [Rafalonso/LoRDeckCodesPython#8]
encode.py
def _encode_card_block(data_stream: BytesIO, cards: List["CardCodeAndCount"]) -> None:
    set_faction_combinations = _get_set_faction_combinations(cards)
    write_varint(data_stream, len(set_faction_combinations))
(+)(+)(+)
set_faction_combinations = sorted(set_faction_combinations, key=lambda y: (len([card for card in cards if card.faction == y[1] and card.set == y[0]]), y[0], y[1]))
(+)(+)(+)

**Comment by shaobaili3** [comment]
I help her to open a new pull request, please refer #9 for details.

Thanks

**Comment by Rafalonso** [comment]
@wangyi041228 Can you give more details about this? What's the context? Why do you need it?

**Comment by wangyi041228** [comment]
Without a standard format, some decks' code generated with Python are different with C# and LoR itself. The difference will make some things more difficult some time.

Standard code:
CIBAIAICBEGRWMIFAEABCFQ5EY3AEAIBAIBQGAIACUQCSAQCAEBBMGADAEAAGBY2

Python without sorting: (try decode then encode the code above)
CIBAKAIACELB2JRWAQAQECINDMYQEAYBAAKSAKIBAEBAGAQDAEAAGBY2AIAQEFQY

Python with sorting:
CIBAIAICBEGRWMIFAEABCFQ5EY3AEAIBAIBQGAIACUQCSAQCAEBBMGADAEAAGBY2

**Comment by Rafalonso** [comment]
I'll give it a more in-depth look tomorrow, thank you for bringing it up

**Comment by Rafalonso** [comment]
Taken care of in #9 thank you very much for contributing
